name: Build Python Exe

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile PDF_DC2.py

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF_DC2-exe
          path: ./dist/PDF_DC2.exe
